DotBots/DotBot-firmware

- drv/protocol.h
- drv/protocol/protocol.c
- projects/03app_dotbot/03app_dotbot.c
- projects/03app_dotbot_gateway/03app_dotbot_gateway.c
- projects/03app_sailbot/03app_sailbot.c
This PR 2 application types, DotBot and SailBot, and modifies the related applications.
fixes #98
> Add header field containing application type

- projects/03app_sailbot/03app_sailbot.c
- projects/03app_sailbot/gps.c
- projects/03app_sailbot/servos.c
The PR fixes warnings when building the SailBot application
> SailBot: Fix warnings

- drv/protocol.h
- projects/03app_dotbot/03app_dotbot.c
> protocol: dotbot: compute direction based using reveiced LH2 positions

- .github/workflows/build.yml
- bsp/nrf52833/pwm.c
- drv/lis2mdl/lis2mdl.c
- projects/01drv_pid/01drv_pid.c
- projects/03app_dotbot/03app_dotbot.c
- projects/03app_sailbot/03app_sailbot.c
- projects/03app_sailbot/gps.c
Tiny change that should allow to check the code formatting with a more recent version of clang-format.
> .github: run style check on Github shared runner

- .github/workflows/build.yml
- Dockerfile
- Makefile
- projects/dotbot-firmware.emProject
> .github: run build job on Github shared runner, add job for build Docker image

- bsp/nrf52833/uart.c
This allows to send payload larger than 64 bytes over UART (limitation due to nrf52840dk uart to USB converter).
> bsp/uart: send large payloads by 64B chunks

- projects/dotbot-firmware.emProject
This is an attempt that fixes #132
> projects: rework release/debug mode optimizations and configuration

- bsp/device.h
- bsp/nrf52833/lh2.c
- projects/03app_dotbot/03app_dotbot.c
> dotbot: refactor main application

- bsp/gpio.h
- bsp/nrf52833/gpio.c
- projects/01bsp_gpio/01bsp_gpio.c
- projects/01bsp_gpio/README.md
- projects/dotbot-firmware.emProject
> bsp: add GPIO bsp library + sample application

- projects/03app_dotbot/03app_dotbot.c
This is a little cleanup required after https://github.com/DotBots/PyDotBot/pull/71 was merged.
> projects/03app_dotbot: stop the motors when receiving new waypoints

- bsp/lh2.h
- bsp/nrf52833/lh2.c
- drv/protocol.h
> bsp/lh2: drv/protocol: only send 2 lh2 raw data in a packet, cleanup lh2 code a bit more

- drv/protocol.h
- projects/03app_dotbot/03app_dotbot.c
Should be merged once https://github.com/DotBots/PyDotBot/pull/79 is merged
> projects/03app_dotbot: add support for new waypoint message format with distance to waypoint threshold

- projects/03app_dotbot_gateway/03app_dotbot_gateway.c
Should be merged once https://github.com/DotBots/PyDotBot/pull/88 is in
> projects/03app_dotbot_gateway: add basic handshake procedure

- bsp/nrf52833/board.c
- bsp/nrf52833/pwm.c
- bsp/nrf52833/uart.c
- projects/03app_dotbot_gateway/03app_dotbot_gateway.c
- projects/dotbot-firmware.emProject
> bsp: projects: use new GPIO API where possible

- .gitignore
- Makefile
- bsp/bsp.emProject
- bsp/nrf/rgbled.c
based on #161 
related to #158
> bsp/rgbled: adapt to nrf5340

- bsp/device.h
- bsp/nrf/clock.c
> bsp/device: bsp/clock: fix and improve clock speed for application core

- bsp/nrf/rpm.c
- projects/03app_nrf5340_app/main.c
> bsp/rpm: adapt to nrf5340 network core

- Makefile
- bsp/device.h
> nrf5340-net: fix device info API + update allowed projects in Makefile

- Makefile
- dotbot-v1.emProject
- drv/drv.emProject
- drv/log_flash.h
- drv/log_flash/log_flash.c
- nrf52833dk.emProject
- nrf52840dk.emProject
- nrf5340dk-app.emProject
- nrf5340dk-net.emProject
- projects/03app_dotbot/03app_dotbot.c
- projects/03app_log_dump/README.md
- projects/03app_log_dump/main.c
- projects/projects-dotbot.emProject
- projects/projects-log-dump.emProject
- sailbot-v1.emProject
> drv: add library for storing log data on flash + add companion application to read and dump logs

- drv/drv.emProject
- drv/protocol.h
- drv/protocol/protocol.c
- projects/03app_dotbot/03app_dotbot.c
- projects/03app_dotbot_gateway/03app_dotbot_gateway.c
- projects/03app_sailbot/03app_sailbot.c
> protocol: extend header with random message id

- bsp/nrf/uart.c
- bsp/uart.h
- projects/01bsp_uart/01bsp_uart.c
- projects/03app_dotbot_gateway/03app_dotbot_gateway.c
- projects/03app_sailbot/gps.c
- testbed/bootloader/main.c
> bsp/uart: extend API to allow using all available UARTE peripherals

- bsp/conf/dotbot_v2_config.h
- bsp/nrf/motors.c
- bsp/nrf/pwm.c
- drv/rgbled_pwm/rgbled_pwm.c
- projects/01drv_rgbled_pwm/01drv_rgbled_pwm.c
> bsp/pwm: drv/rgbled_pwm: various fixes and improvements

- projects/03app_dotbot_gateway/03app_dotbot_gateway.c
Not sure whether that is the correct fix but using a different UART peripheral (here UARTE1) is fixing the issue.
> projects/03app_dotbot_gateway: fix crash on nrf5340dk

- projects/03app_sailbot/03app_sailbot.c
> SailBot: Send radio data outside of the interrupt context

- bsp/bsp.emProject
- bsp/nrf/saadc.c
- bsp/saadc.h
- doc/sphinx/bsp.md
- doc/sphinx/examples.md
- projects/01bsp_saadc/01bsp_saadc.c
- projects/01bsp_saadc/README.md
- projects/projects-bsp-drv.emProject
> bsp: add basic SAADC driver

- Makefile
- bsp/conf/dotbot_v2_config.h
- bsp/conf/nrf52833dk_config.h
- bsp/conf/nrf52840dk_config.h
- bsp/conf/nrf5340dk_config.h
- doc/sphinx/drv.md
- doc/sphinx/examples.md
- drv/drv.emProject
- drv/lis3mdl.h
- drv/lis3mdl/lis3mdl.c
- projects/01drv_lis3mdl/README.md
- projects/01drv_lis3mdl/main.c
- projects/projects-bsp-drv.emProject
> drv: add driver for lis3mdl magnetometer

- doc/sphinx/getting_started.md
> doc: fix DK board names in getting started page

- doc/sphinx/getting_started.md
- projects/03app_dotbot_gateway/03app_dotbot_gateway.c
- LED1 blinks during 1 second during initialization
- LED2 blinks when packets are received from the radio
- LED3 blinks when packets are received from UART
fixes #263
> projects/03app_dotbot_gateway: add user feedback using LEDs

- bsp/bsp.emProject
- bsp/nrf/spim.c
- bsp/spim.h
- doc/sphinx/bsp.md
- doc/sphinx/examples.md
- projects/01bsp_spim/01bsp_spim.c
- projects/01bsp_spim/README.md
- projects/projects-bsp-drv.emProject
> bsp: add SPIM driver

- Makefile
- bsp/board_config.h
- bsp/conf/freebot_v1_0_config.h
- doc/sphinx/applications.md
- drv/protocol.h
- freebot-v1.0.emProject
- projects/03app_freebot/README.md
- projects/03app_freebot/main.c
- projects/projects-freebot-v1.0.emProject
Add initial support KU Leuven FreeBot: https://gitlab.kuleuven.be/u0154762/FreeBotNES
fixes #303
> freebot-v1.0.emProject: add support for FreeBot

- .github/workflows/build.yml
- Makefile
- bsp/nrf/rpm.c
- bsp/nrf/timer.c
- bsp/nrf/timer_hf.c
- bsp/timer.h
- drv/move/move.c
- otap/partition0/main.c
- otap/partition1/main.c
- projects/01bsp_motors/01bsp_motors.c
- projects/01bsp_qdec/01bsp_qdec.c
- projects/01bsp_rgbled/01bsp_rgbled.c
- projects/01bsp_rpm/01bsp_rpm.c
- projects/01bsp_timer/01bsp_timer.c
- projects/01drv_lis3mdl/main.c
- projects/01drv_rgbled_pwm/01drv_rgbled_pwm.c
- projects/03app_dotbot/03app_dotbot.c
- projects/03app_dotbot_gateway/03app_dotbot_gateway.c
- projects/03app_freebot/main.c
- projects/03app_sailbot/03app_sailbot.c
- projects/03app_sailbot/gps.c
> bsp/timer: extend API to allow use of all available RTC peripherals

- bsp/i2c.h
- bsp/nrf/i2c.c
- drv/as5048b/as5048b.c
- drv/ism330/ism330.c
- drv/lis2mdl/lis2mdl.c
- drv/lis3mdl/lis3mdl.c
- drv/lsm6ds/lsm6ds.c
- projects/01bsp_i2c/01bsp_i2c.c
> bsp/i2c: extend API to allow using all available peripherals

- bsp/nrf/i2c.c
- bsp/nrf/spim.c
- bsp/spim.h
- drv/n25q128/n25q128.c
- projects/01bsp_spim/01bsp_spim.c
> bsp/spim: extend API to allow using all available peripherals

- Makefile
- bsp/bsp.emProject
- bsp/nrf/wdt.c
- bsp/wdt.h
- doc/sphinx/bsp.md
- doc/sphinx/examples.md
- projects/01bsp_wdt/README.md
- projects/01bsp_wdt/main.c
- projects/03app_nrf5340_app/main.c
- projects/projects-bsp-drv.emProject
> bsp: add API for watchdog peripheral

- bsp/nrf/radio.c
> bsp/radio: fix TX causing an undesired interrupt + a CRC error

- drv/upgate/upgate.c
- projects/01bsp_nvmc/01bsp_nvmc.c
- projects/03app_log_dump/main.c
This PR fixes build issues raised after upgrading to SES 8.18
> drv/upgate: projects: fix build warning with ses 8.18

- bsp/nrf/uart.c
- projects/03app_dotbot_gateway/03app_dotbot_gateway.c
> projects/03app_gateway: fix application crashing on nrf5340dk

- bsp/nrf/radio_default.c
> Disable whitening for IEEE 8022.15.4 PHY

- bsp/ipc.h
- drv/drv.emProject
- drv/protocol.h
- drv/protocol/protocol.c
- drv/tdma_client.h
- drv/tdma_client/tdma_client_default.c
- drv/tdma_client/tdma_client_nrf5340_app.c
- drv/tdma_server.h
- drv/tdma_server/tdma_server_default.c
- drv/tdma_server/tdma_server_nrf5340_app.c
- projects/01drv_tdma_client/01drv_tdma_client.c
- projects/01drv_tdma_server/01drv_tdma_server.c
- projects/03app_dotbot/03app_dotbot.c
- projects/03app_dotbot_gateway/03app_dotbot_gateway.c
- projects/03app_freebot/main.c
- projects/03app_lh2_mini_mote_app/03app_lh2_mini_mote_app.c
- projects/03app_lh2_mini_mote_test/03app_lh2_mini_mote_test.c
- projects/03app_nrf5340_net/main.c
- projects/03app_sailbot/03app_sailbot.c
- projects/03app_xgo/main.c
> Refactor protocol packets format to enable layering

- bsp/lh2.h
- bsp/nrf/lh2_default.c
- bsp/nrf/lh2_nrf5340_net.c
> Prepare LH2 driver for Swarmit requirements + adapt Non-secure dotbot sample application
