- drv/protocol.h
- projects/03app_sailbot/03app_sailbot.c
This PR adds a simple functionality as part of the autonomous operation of the SailBot. It periodically sends the GPS data over radio within the control loop.
> SailBot: Send GPS data over radio

- bsp/nrf52833/rng.c
- bsp/rng.h
- projects/01bsp_rng/01bsp_rng.c
- projects/01bsp_rng/README.md
- projects/dotbot-firmware.emProject
This adds a simple API to make use of the RNG peripheral on the nrf52.
fixes #101
> bsp: add API for random number generator

- drv/protocol.h
- projects/03app_dotbot/03app_dotbot.c
- projects/03app_dotbot_gateway/03app_dotbot_gateway.c
- projects/dotbot-firmware.emProject
This also adds a new message type to allow to switch the dotbot between manual and automatic control modes.
The refresh rate of the LH2 position is divided by 2: every 100 ms instead of every 50 ms.
Concerning the control loop only the angular speed is adapted using a pid and the linear speed is kept constant for simplicity.
fixes #113 and fixes #121
> Dotbot: implement basic control loop for following a given list of waypoints

- bsp/nrf52833/uart.c
- projects/03app_dotbot_gateway/03app_dotbot_gateway.c
The UART interrupt priority is set to 0 to make sure no byte might be lost.
> dotbot-gateway: refactor to do less things in ISR

- drv/hdlc/hdlc.c
> drv/hdlc: when encoding a payload, escape FCS bytes if needed

- drv/lis2mdl/lis2mdl.c
- drv/protocol.h
- projects/03app_sailbot/03app_sailbot.c
- projects/03app_sailbot/gps.c
The idea is to check if next waypoint is reached in the control_loop and not in the path planner callback. In the end, I just removed the path planner callback because it's simpler to do the GPS coordinates acquisition and check if the next waypoint is reached in the control loop.
fixes #131
> sailbot: add support for user defined waypoints received via protocol packets

- projects/01bsp_radio_lr_txrx/01bsp_radio_lr_txrx.c
- projects/01bsp_radio_txrx/01bsp_radio_txrx.c
- projects/projects.emProject
Loosely related to #158 since with this PR, no modification related to `NRF_P0` is needed to make this work on nrf5340.
> projects/01bsp_radio_*: use gpio API

- bsp/nrf/clock.c
- projects/03app_nrf5340_app/main.c
- correctly configure the LFCLK to use the external 32k crystal
- set the internal capacitance value for the 32MHz crystal
> bsp/clock: improvements in configuration

- bsp/nrf/radio.c
- bsp/nrf/radio_nrf5340_app.c
- bsp/nrf/uart.c
- projects/01bsp_uart/01bsp_uart.c
- projects/01bsp_uart/README.md
- projects/03app_dotbot_gateway/03app_dotbot_gateway.c
- projects/03app_nrf5340_app/main.c
This PR makes it possible to use UART at the highest baudrate (921600 and 1M baud). It also has a positive impact with radio.
> bsp: force constant latency power mode with uart and radio

- bsp/nrf/radio.c
- bsp/nrf/uart.c
- projects/03app_nrf5340_net/main.c
- correctly apply errata 117 when setting BLE mode
- force constant latency power mode only for high UART baudrate
- force constant latency power mode on network core when using companion application
> nrf53: various improvements

- bsp/bsp.emProject
- bsp/nrf/nvmc.c
- bsp/nvmc.h
- projects/01bsp_nvmc/01bsp_nvmc.c
- projects/01bsp_nvmc/README.md
- projects/03app_nrf5340_app/main.c
- projects/projects-bsp-drv.emProject
It's very basic but it allows for erasing, writing and reading data on the flash memory. Where to write, when to erase is left to the user of this library.
It is working on nrf52840, nrf52833 and nrf5340 (application and network cores).
fixes #190
> bsp: add driver for Non Volatile Memory controller

- drv/drv.emProject
- drv/imu.h
- drv/imu/imu.c
- drv/lis2mdl.h
- drv/lis2mdl/lis2mdl.c
- drv/lsm6ds.h
- drv/lsm6ds/lsm6ds.c
- projects/01drv_imu/01drv_imu.c
- projects/01drv_lis2mdl/01drv_lis2mdl.c
- projects/01drv_lsm6ds/01drv_lsm6ds.c
- projects/03app_sailbot/03app_sailbot.c
- projects/projects-bsp-drv.emProject
- projects/projects-sailbot.emProject
The PR modifies LIS2MDL API to offer both uncompensated and tilt-compensated heading. I modify the example project of LIS2MDL to show how to use the tilt-compensated heading together with roll and pitch readings from the accelerometer.
Fixes #188
> Tilt-compensated heading

- projects/03app_dotbot/03app_dotbot.c
- projects/03app_log_dump/README.md
Using log flash has an impact on performance (especially with lighthouse) but is useful for debugging: let's use it on demand using a preprocessor macro at build time.
> projects/03app_dotbot: make log flash use optional (using a preprocessor define)

- Makefile
- bsp/board_config.h
- bsp/bsp.emProject
- bsp/conf/dotbot_v2_config.h
- bsp/conf/nrf5340dk_config.h
- bsp/nrf/qdec.c
- bsp/qdec.h
- projects/01bsp_qdec/01bsp_qdec.c
- projects/01bsp_qdec/README.md
- projects/projects-bsp-drv.emProject
This is a first attempt to add low-level support for qdec. Support only works with nrf5340 because it provides 2 peripherals (one for each motors for example). nrf52 only have one.
fixes #210
based on #206
> bsp: add support for qdec

- bsp/conf/dotbot_v2_config.h
- bsp/conf/nrf52833dk_config.h
- bsp/conf/nrf52840dk_config.h
- bsp/conf/nrf5340dk_config.h
- bsp/nrf/motors.c
- bsp/nrf/pwm.c
- bsp/pwm.h
- drv/drv.emProject
- drv/rgbled_pwm.h
- drv/rgbled_pwm/rgbled_pwm.c
- projects/01drv_rgbled_pwm/01drv_rgbled_pwm.c
- projects/01drv_rgbled_pwm/README.md
- projects/03app_sailbot/servos.c
- projects/projects-bsp-drv.emProject
The PWM API had to be refactored to support multiple PWM peripherals (because they are also used for controlling the DotBot motors for example).
fixes #211
based on #206
> drv: add library to support rgbled via 3 pwm pins

- Makefile
- drv/drv.emProject
- drv/move.h
- drv/move/move.c
- projects/01drv_move/01drv_move.c
- projects/01drv_move/README.md
- projects/projects-bsp-drv.emProject
This PR adds an high level driver library to move a DotBot. The library contains 2 functions:
- to move the dotbot on a straight line given a distance in mm and a speed (negative speed means move backwards)
- to rotate the dotbot with a given angle and a speed
The library is quite basic for the moment: only the left quadratic decoder is used so there's no real-time correction of the motors (pid style).
It can be pretty useful with the control loop to rotate the dotbot prior to move it forward.
> drv: add move library for dotbot (using qdec)

- .readthedoc.yaml
Let's rather publish the documentation there.
fixes #239
> .readthedoc.yaml: add initial configuration

- bsp/nrf/lh2.c
- bsp/nrf/pwm.c
The previously used pin was also used for RGB LED blue pin.
> bsp/lh2: use a truly unused pin for SPI clock

- README.md
- doc/sphinx/getting_started.md
Extend support so it can be used with all DKs supported and both DotBot v1/v2. The links to the latest release hex files are directly given in the page. Also give nrfjprog commands to flash the firmwares as it's IMHO more reliable and still quite easy to install.
TODO:
- Test the nrfjprog commands :)
- Test that the hex files, built in release mode, are functional
> doc: rework getting started page

- .github/workflows/build.yml
tiny cleanup to suppress warning raised when running github actions
> .github: bump actions versions

- drv/as5048b/as5048b.c
- projects/03app_sailbot/03app_sailbot.c
- projects/03app_sailbot/gps.c
- projects/projects-sailbot.emProject
- **Wind sensor reading**: Implements wind sensor reading to the SailBot app, capturing wind data from the encoder. This data is now sent as an extra two-byte packet, aimed for display within the PyDotBot interface ([PyDotBot GitHub](https://github.com/DotBots/PyDotBot/)).
- **Rudder and Sail Trim Data**: Alongside wind data, two additional bytes representing rudder angle and sail trim are sent for compatibility with PyDotBot code updates linked to the SailBot simulator. These changes are pending testing as of the latest commit (`eebda96887a40c91e26c924177b96c2a1a1bfb45`). The rudder angle currently sends as zero. This needs to be changed. 
- **Action Required**: Modifications are necessary to align these new variables (rudder angle and sail trim) with the simulator GUI, including …
> SailBot: Wind Sensor Integration and Bug Fixes

- bsp/nrf/radio.c
The TIFS value was set to 1000us during debugging although the datasheet gives timing values that are at most 140us for a TIFS of 150us.
> bsp/radio: reduce interframe interval

- bsp/nrf/radio.c
Two proposed changes:
- set `TIFS` to 0
- enable Fast TX Ramp Up
This reduces the overhead prep-time of the radio from `370us` to `140us`.
This changes were tested with the project:
- `01bsp_radio_txrx`
- `01bsp_radio_lr_txrx`
Both compile and work correctly
> Enable fastest posible transmission time for the radio

- Makefile
- bsp/nrf/lh2.c
- bsp/nrf/timer_hf.c
- bsp/timer_hf.h
- drv/log_flash/log_flash.c
- otap/bootloader/main.c
- projects/01bsp_i2c/01bsp_i2c.c
- projects/01bsp_radio_txrx/01bsp_radio_txrx.c
- projects/01bsp_rng/01bsp_rng.c
- projects/01bsp_saadc/01bsp_saadc.c
- projects/01bsp_timer_hf/01bsp_timer_hf.c
- projects/01drv_as5048b/01drv_as5048b.c
- projects/01drv_ism330/01drv_ism330.c
- projects/01drv_pid/01drv_pid.c
- projects/03app_log_dump/main.c
- projects/03app_xgo/main.c
> bsp/timer_hf: extend api so all available timer peripherals can be used

- bsp/lh2.h
- bsp/nrf/lh2.c
> lh2_mocap: Add mocap detection functions to the lh2 driver

- bsp/nrf/radio_nrf5340_app.c
- bsp/nrf/rng_nrf5340_app.c
- nRF/System/nRF5340_xxAA_Application_cpu.c
- projects/03app_nrf5340_app/main.c
- projects/03app_nrf5340_net/main.c
> nrf53: cleanup all trustzone rights given to network core peripherals

- bsp/clock.h
- bsp/gpio.h
- bsp/nrf/i2c.c
- bsp/nrf/lh2_default.c
- bsp/nrf/nvmc.c
- bsp/nrf/partition.c
- bsp/nrf/pwm_default.c
- bsp/nrf/qdec.c
- bsp/nrf/qspi.c
- bsp/nrf/rpm.c
- bsp/nrf/saadc.c
- bsp/nrf/spim.c
- bsp/nrf/timer.c
- bsp/nrf/timer_hf.c
- bsp/nrf/uart.c
- bsp/nrf/wdt.c
- nRF/System/cpu.c
This PR is useful for building dotbot-firmware based application compatible with [swarmit](https://github.com/DotBots/swarmit).
Just add `NRF_TRUSTZONE_NONSECURE` CFLAGS to the build project.
depends on #334, #335 and #336
> bsp: add support for non secure peripherals on application core

- bsp/nrf/radio_default.c
- bsp/radio.h
- projects/01bsp_radio_txrx/01bsp_radio_txrx.c
When `NRF_RADIO->PCNF0 |= (RADIO_PCNF0_CRCINC_Exclude << RADIO_PCNF0_CRCINC_Pos)`, meaning the CRC is not included in the payload, communication between nRF devices works correctly with CRC checking. Each nRF device expects the two bytes following the payload to be the CRC.  
However, when communicating with other IEEE 802.15.4 PHY-compliant devices, the physical layer only reads the total number of bytes specified by the length field. It does not check the CRC correctly or may mistakenly use the last two bytes of the payload as the CRC instead of the actual CRC bytes.  
For example, when transmitting the packet `{ 0x31, 0x32, 0x33 }` (with `length = 3` bytes), the actual transmitted data is:  
```
Payload: [0x31, 0x32, 0x33]
CRC: [0x78, 0x5a]
Total: 5 bytes (but frame length = 3)
``` …
> IEEE 802.15.4 PHY: changes on CRC handling to make it protocol compliant

- .github/workflows/build.yml
The docker image cannot be built anymore automatically from GHA because SEGGER requires authentication to download  the SES archive.
> .github: disable docker build

- bsp/nrf/gpio.c
- drv/hdlc/hdlc.c
- drv/protocol.h
Some minor changes are required to keep the DotBot-firmware compatible with PyDotBot after https://github.com/DotBots/PyDotBot/pull/154 is merged
> drv/protocol: update to make it compatible with swarmit version and packet types

- bsp/nrf/timer.c
- bsp/nrf/timer_hf.c
This  improves a lot the reliability of the UART to radio gateways when timers are used with time slotted network stacks (TDMA, mira)
> bsp/nrf/timer: set lower priority to timers

- bsp/nrf/board.c
During tests of the motors on DOTBOT_V3, I found that motor rotation is enabled when driving the control pin _db_gpio_clear_, rather than _db_gpio_set_.
> bsp/board: correct motor_en active-low init for DOTBOT_V3
